config/routes.rb
Rails.application.routes.draw do

  resources :walls
  resources :nodes
  devise_for :users
  resources :images, only: [:create, :destroy]

  root 'nodes#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
	attachment :image
end

app/models/node.rb
class Node < ActiveRecord::Base
	belongs_to :user
	belongs_to :wall
	acts_as_tree
	validates :title,:presence => {:message => "Write a name"}, :allow_blank => false

	extend ActsAsTree::TreeWalker

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  acts_as_token_authenticatable

  has_many :nodes, dependent: :destroy
  has_many :walls, dependent: :destroy

  def get_authentication_token
	self.save if self.authentication_token.blank?
	return self.authentication_token
  end

  def share_link(url)
  	url+'?user_email='+self.email+'&user_token='+ self.get_authentication_token
  end
end

app/models/wall.rb
class Wall < ActiveRecord::Base
	belongs_to :user
	has_many :nodes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # acts_as_token_authentication_handler_for User

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  protect_from_forgery except: :create
 
  def create
    @image = Image.new(image_params)
    @image.save
 
    respond_to do |format|
      format.json { render :json => { url: Refile.attachment_url(@image, :image), image_id: @image.image_id } }
    end
  end
 
  def destroy
    # @image = Image.find_by(image_id: params[:id])
    # @image.destroy
    # respond_to do |format|
    #   format.json { render :json => { status: :ok } }
    # end
  end
  
  private
 
  def image_params
    params.require(:image).permit(:image)
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]
  acts_as_token_authentication_handler_for User, only: [:new, :create, :update, :destroy, :index] 


  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = current_user.nodes
    @walls = current_user.walls
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    if params['format']
      @node = Node.find(params['format']).children.create(user_id: current_user.id, title: 'New Node')
    else
      @node = current_user.nodes.new(title: 'New Node', wall_id: params['wall'])
    end
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = current_user.nodes.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to wall_or_root_path(@node), notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to wall_or_root_path(@node), notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Return wall_path of the root node, or root_path if there is no wall
    def wall_or_root_path(node)
      return_path = if wall = node.root.wall
                      wall_path(wall)
                    else                
                      root_path
                    end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
      @current_wall = @node.root.wall
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:title, :body, :parent_id, :wall_id)
    end
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_action :set_wall, only: [:show, :edit, :update, :destroy]
  acts_as_token_authentication_handler_for User, except: [:show] 


  # GET /walls
  # GET /walls.json
  def index
    @walls = Wall.all
  end

  # GET /walls/1
  # GET /walls/1.json
  def show
    @current_wall = Wall.find(params['id'])

    @walls = user_walls
        
    @nodes = @current_wall.nodes
  end

  # GET /walls/new
  def new
    @wall = current_user.walls.new(name: 'New Wall')
  end

  # GET /walls/1/edit
  def edit
  end

  # POST /walls
  # POST /walls.json
  def create
    @wall = current_user.walls.new(wall_params)

    respond_to do |format|
      if @wall.save
        format.html { redirect_to @wall, notice: 'Wall was successfully created.' }
        format.json { render :show, status: :created, location: @wall }
      else
        format.html { render :new }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walls/1
  # PATCH/PUT /walls/1.json
  def update
    respond_to do |format|
      if @wall.update(wall_params)
        format.html { redirect_to @wall, notice: 'Wall was successfully updated.' }
        format.json { render :show, status: :ok, location: @wall }
      else
        format.html { render :edit }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walls/1
  # DELETE /walls/1.json
  def destroy
    @wall.destroy
    respond_to do |format|
      format.html { redirect_to walls_url, notice: 'Wall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall
      @wall = Wall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_params
      params.require(:wall).permit(:name)
    end

    # This method gets the user walls even if the user hasn't signed
    # in because is a guest
    def user_walls
      if current_user
        @walls = current_user.walls
      elsif email = params['user_email']
        @walls = User.find_by(email: email).walls
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/image/create.html.erb
<h1>Image#create</h1>
<p>Find me in app/views/image/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Treeview</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">








	<!-- tree -->
	<style type="text/css">
		ul.tree {
			overflow-x: auto;
			white-space: nowrap;  
		}
		ul.tree,
		ul.tree ul {
			width: auto;
			margin: 0;
			padding: 0;
			list-style-type: none;
		}
		ul.tree li {
			display: block;
			width: auto;
			float: left;
			vertical-align: top;
			padding: 0;
			margin: 0;
		}
		ul.tree ul li {
			background-image: url(data:image/gif;base64,R0lGODdhAQABAIABAAAAAP///ywAAAAAAQABAAACAkQBADs=);
			background-repeat: repeat-x;
			background-position: left top;
		}
		ul.tree li span {
			display: block;
			width: 5em;
	  /*
	    uncomment to fix levels
	    height: 1.5em;
	    */
	    margin: 0 auto;
	    text-align: center;
	    white-space: normal;
	    letter-spacing: normal;
	}
</style>
<!--[if IE gt 8]> IE 9+ and not IE -->
<style type="text/css">
	ul.tree ul li:last-child {
		background-repeat: no-repeat;
		background-size:50% 1px;
		background-position: left top;
	}
	ul.tree ul li:first-child {
		background-repeat: no-repeat;
		background-size: 50% 1px;
		background-position: right top;
	}
	ul.tree ul li:first-child:last-child {
		background: none;
	}
	ul.tree ul li span {
		background: url(data:image/gif;base64,R0lGODdhAQABAIABAAAAAP///ywAAAAAAQABAAACAkQBADs=) no-repeat 50% top;
		background-size: 1px 0.8em;
		padding-top: 1.2em;
	}
	ul.tree ul {
		background: url(data:image/gif;base64,R0lGODdhAQABAIABAAAAAP///ywAAAAAAQABAAACAkQBADs=) no-repeat 50% top;
		background-size: 1px 0.8em;
		margin-top: 0.2ex;
		padding-top: 0.8em;
	}
</style>
<!-- <[endif]-->
	<!--[if lte IE 8]>
	<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
	<script type="text/javascript">
	    /* Just to simplify HTML for the moment.
	     * This could easily be replaced by inline classes.
	     */
	    $(function() {
	      $('li:first-child').addClass('first');
	      $('li:last-child').addClass('last');
	      $('li:first-child:last-child').addClass('lone');
	    });
	</script>
	<style type="text/css">
	ul.tree ul li {
	  background-image: url(pixel.gif);
	}
	ul.tree ul li.first {
	  background-image: url(left.gif);
	  background-position: center top;
	}
	ul.tree ul li.last {
	  background-image: url(right.gif);
	  background-position: center top;
	}
	ul.tree ul li.lone {
	  background: none;
	}
	ul.tree ul li span {
	  background: url(child.gif) no-repeat 50% top;
	  padding-top: 14px;
	}
	ul.tree ul {
	  background: url(child.gif) no-repeat 50% top;
	  margin-top: 0.2ex;
	  padding-top: 11px;
	}
	</style>
	<[endif]-->

	<!-- page presentation -->
	<style type="text/css">
		body {
			font-family:sans-serif;
			color: #666;
			text-align: center;
		}
		A, A:visited, A:active {
			color: #c00;
			text-decoration: none;
		}
		A:hover {
			text-decoration: underline;
		}
		ul.tree,
		#wrapper {
			width: 960px;
			margin: 0 auto;
		}
		ul.tree {
			width: 650px;
		}
		.clearer {
			clear: both;
		}
		p {
			margin-top: 2em;
		}
	</style>









</head>
<body style="">
	<div class="header" style="height:20px">
		<div id="login_user_status" style="float:right;">

			<% if user_signed_in? %> 
			<%= current_user.email  %>  
			| 
			<%= link_to "Sign out", destroy_user_session_path, :method => :delete%> 
			<% else %> 
			<em>Not Signed in.</em> 
			<%= link_to 'Sign in', new_user_session_path%> 
			or 
			<%= link_to 'Sign up', new_user_registration_path%> 
			<% end %> 
		</div>
		<div style="float:left;">
			<%= link_to "🏡  Home", root_path %> 
			<% if @current_wall %>
				> 
				<%= link_to @current_wall.name, wall_path(@current_wall) %>
			<% end -%>
		</div>
	</div>

	<%= yield %>

</body>
</html>

app/views/nodes/_form.html.erb
 <%= form_for(@node) do |f| %>
<% if @node.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

  <ul>
    <% @node.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<h1 class="node-header"> <%= f.text_field :title, {class: 'node-title'} %> </h1>
<div class="field" style="text-align:left;">
<%= f.trix_editor :body, :class => "trix-content"%>
</div>

<% if params[:action] == 'edit' %>
  <div id="select_change_branch" style="margin-bottom: 8px;">
    Parent:
    <%= f.collection_select(:parent_id, Node.all, :id, :title, :include_blank => true) %>
  </div>
<% end %>

<%= f.hidden_field :wall_id %> 

<div class="actions">
  <%= f.submit 'Save', {class: 'btn-success btn'}%>
</div>
<% end %>



<style>
  trix-toolbar {
    text-align: center;
  }

</style>

app/views/nodes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', nodes_path %> |
<a href="#" id="btn_change_branch">Change Parent</a> &#x1F474; |
<%= link_to 'New Child', new_node_path(@node) %> &#x1F476; | 
<a href="#" id="demo" onclick="copyToClipboard(document.getElementById('demo').innerHTML)">Share 🔗</a> |
<%= link_to 'Delete', @node, method: :delete, data: { confirm: 'Are you sure?' } %>




<script>
  function copyToClipboard(text) {
  	var link = '<%=@node.user.share_link(request.original_url) %>'
    window.prompt("Copy to clipboard: Ctrl+C, Enter", link);
  }
</script>



<script type="text/javascript">
	$(function() {
	    $("#select_change_branch").hide();
	    $("#btn_change_branch").click(function(event) {
	        event.preventDefault();
	        $("#select_change_branch").toggle();
	    });
	});

	
</script>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1> The place to think 😊</h1>


<ul class="tree" style="display: inline-block; width: auto; margin-top: 50px;">

      <% previous_level = 0 %>
      <% @nodes.walk_tree do |node, level| %>

        <% if level < previous_level %>
          <!-- Up a level -->
          <% (previous_level-level).times do %>
            </li></ul>
          <% end %>
        <% end %>

        <li> 
        <span style="min-width: 120px;"><%= link_to "#{node.title}", edit_node_path(node) %></span>

        <% unless node.body.nil? or node.body.empty? %>
         📦 
        <% end %>

        <% if node.children.any? %>
          <ul>
        <% else %>
          </li>
        <% end %>

        <% previous_level = level %>
      <% end %>

      <% previous_level.times do %>
        </li></ul>
      <% end %>

</ul>
<br>
<%= link_to '+ New Tree', new_node_path, {class: 'fav-button'} %>
<div style="position:fixed; bottom:10px; left:10px;">
  <%= link_to '+ New Wall', new_wall_path, {class: 'bottom-left-button'} %>
  <% if !@walls.blank? %>
    <% for wall in @walls %>
      <div style="float:left;"> &nbsp;| &nbsp;</div>
      <%= link_to wall.name, wall_path(wall), {class: 'bottom-left-button'} %>
    <% end %>
  <% end %>
</div>

app/views/nodes/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
 <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
    <%= @node.title %>
    <%= @node.body %>
</p>

<div>hello<br><br><a href="/attachments/store/4f4a24fffa75e73718ad58ffd1b46ecb65d099f3c94b8a849b596aff312a/Screen+Shot+2016-09-16+at+10.55.14.png" data-trix-attachment="{&quot;contentType&quot;:&quot;image/png&quot;,&quot;filename&quot;:&quot;Screen Shot 2016-09-16 at 10.55.14.png&quot;,&quot;filesize&quot;:335804,&quot;height&quot;:481,&quot;href&quot;:&quot;/attachments/store/4f4a24fffa75e73718ad58ffd1b46ecb65d099f3c94b8a849b596aff312a/Screen+Shot+2016-09-16+at+10.55.14.png&quot;,&quot;image_id&quot;:&quot;4f4a24fffa75e73718ad58ffd1b46ecb65d099f3c94b8a849b596aff312a&quot;,&quot;url&quot;:&quot;/attachments/store/4f4a24fffa75e73718ad58ffd1b46ecb65d099f3c94b8a849b596aff312a/Screen+Shot+2016-09-16+at+10.55.14.png&quot;,&quot;width&quot;:1164}" data-trix-content-type="image/png"><figure class="attachment attachment-preview png"><img src="/attachments/store/4f4a24fffa75e73718ad58ffd1b46ecb65d099f3c94b8a849b596aff312a/Screen+Shot+2016-09-16+at+10.55.14.png" width="1164" height="481"><figcaption class="caption">Screen Shot 2016-09-16 at 10.55.14.png <span class="size">327.93 KB</span></figcaption></figure></a></div>  

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'New Branch', new_node_path(@node) %> | 
<%= link_to 'Delete', @node, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', nodes_path %>

app/views/walls/_form.html.erb
<%= form_for(@wall) do |f| %>
  <% if @wall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wall.errors.count, "error") %> prohibited this wall from being saved:</h2>

      <ul>
      <% @wall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1> <%= f.text_field :name, {class: 'node-title'} %></h1>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/walls/edit.html.erb
<h1>Editing Wall</h1>

<%= render 'form' %>

<%= link_to 'Show', @wall %> |
<%= link_to 'Back', walls_path %>

app/views/walls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Walls</h1>

<table style="text-align:center;">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @walls.each do |wall| %>
      <tr>
        <td><%= link_to wall.name, wall %></td>
        <td><%= link_to 'Show', wall %></td>
        <td><%= link_to 'Edit', edit_wall_path(wall) %></td>
        <td><%= link_to 'Destroy', wall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wall', new_wall_path %>

app/views/walls/new.html.erb
<h1>New Wall</h1>

<%= render 'form' %>

<%= link_to 'Back', walls_path %>

app/views/walls/show.html.erb
<h1><%= @current_wall.name %> <a href='#' style="background:none; text-decoration:none;font-size: 20px;opacity: 0.5;
;
" id="demo" onclick="copyToClipboard(document.getElementById('demo').innerHTML)">🔗</a></h1>

<p id="notice"><%= notice %></p>
<ul class="tree" style="display: inline-block; width: auto; margin-top: 25px;">

      <% previous_level = 0 %>
      <% @nodes.each do |root| %>

        <li> 
        <span style="min-width: 120px;"><%= link_to "#{root.title}", edit_node_path(root) %></span>

        <% unless root.body.nil? or root.body.empty? %>
         📦 
        <% end %>

        <% if root.children.any? %>
          <ul>
        <% else %>
          </li>
        <% end %>


        <% root.walk_tree do |node, level| %>

          <% if level < previous_level %>
            <!-- Up a level -->
            <% (previous_level-level).times do %>
              </li></ul>
            <% end %>
          <% end %>

          <li> 
          <span style="min-width: 120px;"><%= link_to "#{node.title}", edit_node_path(node) %></span>

          <% unless node.body.nil? or node.body.empty? %>
           📦 
          <% end %>

          <% if node.children.any? %>
            <ul>
          <% else %>
            </li>
          <% end %>

          <% previous_level = level %>
        <% end %>

      <% end %>

      <% previous_level.times do %>
        </li></ul>
      <% end %>

</ul>
<br>
<%= link_to '+ New Tree', new_node_path(:wall => @current_wall), {class: 'fav-button'} %>
<div style="position:fixed; bottom:10px; left:10px;">
  <%= link_to '+ New Wall', new_wall_path, {class: 'bottom-left-button'} %>
  <% if !@walls.blank? %>
    <% for wall in @walls %>
      <div style="float:left;"> &nbsp;| &nbsp;</div>
      <%= link_to wall.name, wall_path(wall), {class: 'bottom-left-button'} %>
    <% end %>
  <% end %>
</div>

<script>
  function copyToClipboard(text) {
    var link = '<%=@wall.user.share_link(request.original_url) %>'
    window.prompt("Copy to clipboard: Ctrl+C, Enter", link);
  }

</script>